# Generated by Django 2.2.7 on 2019-11-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treyeurl',
            name='shortcode',
            field=models.CharField(default='abc123', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
