# Generated by Django 2.1.7 on 2019-11-08 05:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_treyeurl_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='treyeurl',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treyeurl',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
