# Generated by Django 2.2.7 on 2019-11-08 23:45

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0005_auto_20191108_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treyeurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortner.validators.validate_url, shortner.validators.validate_dot_com]),
        ),
    ]
