# Generated by Django 2.2.7 on 2019-11-14 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0007_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
